### ISSUE TITLE
Bash prompt refresh

### ISSUE THREAD

**Issue by vifon** [Vifon/texas#1]
Currently the working directory in Bash's prompt isn't updated until the next prompt redraw. It should be redrawn right after changing the working directory. Any advice how to solve this issue is very welcome.

**Comment by d630** [comment]
Hmm, the working directory is not updated either. I think, `texas--ranger-to-sh-sync` will not be running, until the next command execution happens. You can see it with

``` sh
TEXAS_SHELL_PID=$$
TEXAS_RANGER_PID=$(tmux split-window -p 30 -b -P -F '#{pane_pid}' "TEXAS_SHELL_PID=$TEXAS_SHELL_PID ranger")

texas--ranger-to-sh-sync() {
        builtin cd -P /proc/$TEXAS_RANGER_PID/cwd
        >> /tmp/debug-texas \
        printf "%s\n" "$(date +%s) TEXAS_RANGER_PID=$TEXAS_RANGER_PID TEXAS_SHELL_PID=$TEXAS_SHELL_PID ppid=$PPID pid=$$ cwd:$PWD"
}
```

and following it in a second tty:

``` sh
> /tmp/debug-texas ; tail -f /tmp/debug-texas
```

Try a `read` in bash. Or this:

``` sh
while sleep 3 ; do echo $PWD ; done
```

**Comment by vifon** [comment]
Hm... I think the working directory itself is being updated but not the `$PWD` variable. `ls` seems to list the files in the correct (changed) working directory and `pwd` prints the correct directory. Deferring the signal handlers until the next command would be a really strange thing to do.

Sadly, I still have no idea how to refresh Bash current state. I'm considering erasing the current prompt and reprinting it in a signal handler but this is a horrible "solution". And there seems to be no way to print `$PS1` just as Bash would print it normally (like `print -P` in zsh).

**Comment by d630** [comment]
Seems to be a good question/problem for the bash mailing list...

Anyway. Super useful extension! :smile:

**Comment by vifon** [comment]
Ok, so I've asked about this issue on #bash on Freenode. It seems `texas` would need some changes in how the window focus is changed and it could easily turn into a very leaky abstraction. I'll have to think this problem through. I'll leave it as it is for now.

Thanks. :)

**Comment by d630** [comment]
I far I can see, the trap on SIGUSR1 will not be executed until the "current command" completes.  While in an interactive session on the prompt, the "current command" ends, when you type something on the prompt and let it follow an enter (like asking for a value in the end of a while-loop; the "current command" would be than one loop).

In terminal A do:

``` sh
__texas () { eval echo "'(in __texas)': _: $_" ; cd -P / ; }
__debug () { echo "DEBUG executed (trap: debug): wd: '$(pwd)' bcmd: '$BASH_COMMAND' _: '$_'" ; }
trap __debug DEBUG
trap __texas USR1
echo PP=$$
cd ~
```

In terminal B do:

``` sh
kill -s SIGUSR1 PP
( cd -P /proc/PP/cwd ; pwd -P )
```

Back in A, I get after typing 'ls':

``` sh
DEBUG executed (trap: debug): wd: '/home/user1' bcmd: 'cd' _: 'cd'
(in texas): _: __debug
DEBUG executed (trap: debug): wd: '/' bcmd: 'ls -h --color=auto' _: '__texas'
bin  boot  dev  etc  home  initrd.img  initrd.img.old  lib  lib64  lost+found  media  mnt  proc  root  run  sbin  srv  sys  tmp  usr  var  vmlinuz  vmlinuz.old
```

So, the only thing coming to my mind is to let SIGUSR1 follow a SIGINT

**Comment by vifon** [comment]
Wow, you're right! Not the cleanest solution but I really cannot complain if it's the only one working. Thanks a lot! I'll push an update in a few minutes.
