### ISSUE TITLE
Option to place shell below ranger

### ISSUE THREAD

**Issue by teranex** [Vifon/texas#4]
Would it be possible to optionally place the shell below ranger instead of on top?

**Comment by vifon** [comment]
That was my original intention but I changed it for the sake of compatibility with the older tmux versions. Now it's customizable (and still should work with tmux 1.8+).

**Comment by teranex** [comment]
I'm on tmux 2.2 and by default the shell is focused when launching Texas. This seems to be because of the `-d` option, if I remove this ranger is focused by default.
Also see my comment in the code: https://github.com/Vifon/texas/commit/caae0fb7813036902a1a2619d885836b4b2619fa#commitcomment-20946296. I only saw your commit message after adding the comment, sorry.

**Comment by vifon** [comment]
The behavior of `swap-pane` seems to be all over the place between the tmux versions. I'm not sure how to resolve it. I'll try to test some more tmux versions. Maybe it's broken in my 2.1.

**Comment by vifon** [comment]
It seems the behavior is different only on tmux `2.1`.
Every other version I tested (`1.8`, `2.0`, `2.2` and `2.3`) behaves like you described.

Fixed.
