### ISSUE TITLE
Allow configuration of pane-sizes

### ISSUE THREAD

**Issue by teranex** [Vifon/texas#5]
Would it be possible to add an option to specify the height of the shell pane in number of lines?

Additionally what would be really cool is if the shell pane could automatically resize, to a certain percentage of the screen, when it gets the focus, and back to the original size when ranger is focused again. Not sure if that is possible though.

**Comment by vifon** [comment]
Your second request *might* be possible if the user would exclusively use the custom texas hotkey (<kbd>C-o</kbd>, I should make it customizable). In my opinion it would cause more trouble than it's worth as I don't see a way to implement it in a more robust manner. Sorry.

**Comment by teranex** [comment]
Thanks for the configuration option.
At first I was confused why the options didn't work when I did `TEXAS_CONFIG_SIZE=90 texas`, but after adding them to my .zshrc it works and it makes sense ofcourse since texas runs in a new shell inside tmux.

**Comment by vifon** [comment]
It would work if the variable would be exported. The shell inside tmux would inherit it.

**Comment by teranex** [comment]
Yes that's something I also tried `export TEXAS_CONFIG_SIZE=90; texas` but that didn't really seem to work either. But I added everything to my .zshrc and that works so no problem. Many thanks for the changes :)

**Comment by vifon** [comment]
`export TEXAS_CONFIG_SIZE=90; texas` works for me, FWIW.
